from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_crateModel(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(604, 498)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.modelNameLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.modelNameLabel.setFont(font)
        self.modelNameLabel.setObjectName("modelNameLabel")
        self.horizontalLayout.addWidget(self.modelNameLabel)
        self.modelNameLineEdit = QtWidgets.QLineEdit(Form)
        self.modelNameLineEdit.setObjectName("modelNameLineEdit")
        self.horizontalLayout.addWidget(self.modelNameLineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.imageNameLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.imageNameLabel.setFont(font)
        self.imageNameLabel.setObjectName("imageNameLabel")
        self.horizontalLayout_4.addWidget(self.imageNameLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.imageListWidget = QtWidgets.QListWidget(Form)
        self.imageListWidget.setObjectName("imageListWidget")
        self.verticalLayout.addWidget(self.imageListWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.imageAddButton = QtWidgets.QPushButton(Form)
        self.imageAddButton.setObjectName("imageAddButton")
        self.horizontalLayout_2.addWidget(self.imageAddButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.imageDeleteButton = QtWidgets.QPushButton(Form)
        self.imageDeleteButton.setObjectName("imageDeleteButton")
        self.horizontalLayout_2.addWidget(self.imageDeleteButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.xmlNameLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.xmlNameLabel.setFont(font)
        self.xmlNameLabel.setObjectName("xmlNameLabel")
        self.horizontalLayout_6.addWidget(self.xmlNameLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.xmlListWidget = QtWidgets.QListWidget(Form)
        self.xmlListWidget.setLineWidth(5)
        self.xmlListWidget.setObjectName("xmlListWidget")
        self.verticalLayout_2.addWidget(self.xmlListWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.xmlAddButton = QtWidgets.QPushButton(Form)
        self.xmlAddButton.setObjectName("xmlAddButton")
        self.horizontalLayout_3.addWidget(self.xmlAddButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.xmlDeleteButton = QtWidgets.QPushButton(Form)
        self.xmlDeleteButton.setObjectName("xmlDeleteButton")
        self.horizontalLayout_3.addWidget(self.xmlDeleteButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.line = QtWidgets.QFrame(Form)
        self.line.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.line.setFont(font)
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(5)
        self.line.setMidLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.nextButton = QtWidgets.QPushButton(Form)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout_5.addWidget(self.nextButton)
        self.cancleButton = QtWidgets.QPushButton(Form)
        self.cancleButton.setObjectName("cancleButton")
        self.horizontalLayout_5.addWidget(self.cancleButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.modelNameLabel.setText(_translate("Form", "Model Name :"))
        self.imageNameLabel.setText(_translate("Form", "Image File :"))
        self.imageAddButton.setText(_translate("Form", "Add"))
        self.imageDeleteButton.setText(_translate("Form", "Delete"))
        self.xmlNameLabel.setText(_translate("Form", "XML File:"))
        self.xmlAddButton.setText(_translate("Form", "Add"))
        self.xmlDeleteButton.setText(_translate("Form", "Delete"))
        self.nextButton.setText(_translate("Form", "Next"))
        self.cancleButton.setText(_translate("Form", "Cancle"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EVALUATETeam = QtWidgets.QWidget()
    ui = Ui_crateModel()
    ui.setupUi(EVALUATETeam)
    EVALUATETeam.show()
    sys.exit(app.exec_())